### ISSUE TITLE
Logo Design Project Proposal

### ISSUE THREAD

**Issue by debpedrano** [NearbyShops/Nearby-Shops-Android-app#1]
Greetings to you Project Owner!

I am a graphics designer who make logo for GitHub projects, I am not a professional one but I can give you a good quality output. It would be a benefit to the project since it is getting bigger and bigger, so its on you to decide if you need it. Just mention me in the comment section and lets discuss about it.

**Comment by SumeetMoray** [comment]
hi, sorry for such a late reply. I didn't received any notification from github about your message.

Yes we surely need designers.  If you contribute i will mention your name as a project contributor. 

Get in touch with me ... we will discuss about it !

**Comment by SumeetMoray** [comment]
THanks happy holidays to you also. 

This project is a mobile based ecommerce software for local shopping needs. It's like an app which helps you buy fruits, vegetables and anything from shops located near to you. 

I am making a list of the kind of contributions we need in this project and also working on a contributor policy so i will get in touch with you shortly after i finish with this list ... and i will discuss with you in detail ... various options where you can contribute ...

**Comment by debpedrano** [comment]
@SumeetMoray 

How was it?
![image](https://user-images.githubusercontent.com/40510200/50504198-e25b6480-0aa6-11e9-9f92-1ab21b6b8930.png)

**Comment by debpedrano** [comment]
That logo is for free, all you need to do is to use it on your GitHub project :) nothing else.. or maybe use it on the official site, this is my way of practicing tho

**Comment by debpedrano** [comment]
@SumeetMoray  you can use my logo on your GitHub project, payment is not a problem. Everything is for free, all you need to is use it and credits me. That's all , have a nice day!

**Comment by SumeetMoray** [comment]
okay fine ... deb ... i will take your logo for one app ... and add your name in the credits section ... if possible send me few more samples ...
