### ISSUE TITLE
project not showing module for running

### ISSUE THREAD

**Issue by nilnilnilesh** [NearbyShops/Nearby-Shops-Android-app#13]
Hello,
I am trying to import your project in android studio but its not running showing as "Add Configuration". Run and Debug buttons are disabled.

**Comment by SumeetMoray** [comment]
hi nilesh ... 

I just cloned the repository and opened it in the android studio and it is working okay on my side ... are you using the latest android studio ... the current version which i am using is android studio 3.5 rc3

**Comment by nilnilnilesh** [comment]
Yes. Latest Beta version of android is worst.. sorry to bother you.
