### ISSUE TITLE
Remove hardcoded messages and labels

### ISSUE THREAD

**Issue by abajorat** [NearbyShops/Nearby-Shops-Android-app#18]

**Comment by abajorat** [comment]
@SumeetMoray 
How can I activate the Portuguese language? Doing so I would be easily able to find all hardcoded (english) strings and put them into the strings.xml

**Comment by SumeetMoray** [comment]
You need set Portuguese as default language on your device (phone)

Then it automatically shows Portuguese translations

**Comment by abajorat** [comment]
wow, that's really nice
