### ISSUE TITLE
App not open

### ISSUE THREAD

**Issue by robson-alcantara** [NearbyShops/Nearby-Shops-Android-app#23]
The application does not open on my Samsung S4 mini or AVD emulator (Nexus 5 and Android 7)

**Comment by SumeetMoray** [comment]
Is it an emulator or a real device ? Try to install on a real device.

**Comment by robson-alcantara** [comment]
The AVD emulator (Nexus 5 and Android 7) is a emulator. The Samsung S4 mini is a real hardware with Android 4.4

**Comment by SumeetMoray** [comment]
We generally dont use emulators during development !

Android 4.4 its API level 19 ... its the lowest level our app supports. Can you check installing the app on higher than 4.4 !

**Comment by robson-alcantara** [comment]
The problem is okhttp3. The versions upper to the 3.12 only suports api level >= 21
