### ISSUE TITLE
Price's set  for products by platform  admin doesn't reflect in shop admin's  product list.

### ISSUE THREAD

**Issue by crampal7** [NearbyShops/Nearby-Shops-Android-app#27]
The shop admin needs to set prices for every item.  It would be better if the shop owner is left with lesser work

**Comment by SumeetMoray** [comment]
ok ... i have one idea ... Shop admin will set MRP and if shop owner does not set the price then MRP will automatically be considered as the item price !

**Comment by crampal7** [comment]
Yes, this is the best preferred way

**Comment by SumeetMoray** [comment]
Ok fixed ... Done ! ... added this feature ... i will push the update and it will be available after you update the server !
