### ISSUE TITLE
Tipping services

### ISSUE THREAD

**Issue by WizardKid** [NearbyShops/Nearby-Shops-Android-app#3]
Hi in the current atmosphere this is a great app. However, my interest lies on the concept of “instacart”. Does this service offer a tipping service such as a user sees an order or request with a tip highlighted then accept that as a job request to collect the shopping place by an individual?

**Comment by SumeetMoray** [comment]
Yes currently support delivery by vendors ... delivery by staff employed by market  ... (instacart shoppers) with an option to tip them ... we will be adding this feature very soon ... 

Its going to be added very soon !

**Comment by WizardKid** [comment]
Ok thank you for responding. My main interest in setting up this service would be the instacart feature. Will try it out but will until the feature is added before putting it in production.

**Comment by SumeetMoray** [comment]
Sure try it out ... And you and put into production after the tipping feature is implemented !
