### ISSUE TITLE
Dockerise the application for easier setup [Low priority]

### ISSUE THREAD

**Issue by apnerve** [NearbyShops/Nearby-Shops-Android-app#7]
It think it would be really useful for the developers who'd want to contribute if the application is dockerised. I'll try to do it and send a PR

**Comment by SumeetMoray** [comment]
Yes that will be great ... dockerizing was on my list of features to have ... but due to lot of workload i was not able to do it ... if you can do it ... that will be good ...

**Comment by SumeetMoray** [comment]
The docker image has been created and there is now a docker installation guide made available also at this link : https://developer.nearbyshops.org/installation/installation-guide-quick-docker.html
